Django-FastApi-Integration/django-project/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
]

Django-FastApi-Integration/django-project/products/urls.py
from django.urls import path
from . import views
app_name = 'products'
urlpatterns = [
    path('',views.product_list,name='product_list'),
    path('products/create',views.product_create,name='product_create'),
    path('products/<int:product_id>/edit',views.product_edit,name='product_edit'),
    path('products/<int:product_id>/delete',views.product_delete,name='product_delete'),
]

Django-FastApi-Integration/django-project/products/models.py
from django.db import models

# Create your models here.

Django-FastApi-Integration/django-project/products/forms.py
# 화면구성을 클래스형태로 구현해서 html에서 표시   ----.html 을 대신
from django import forms

class ProductForm(forms.Form):
    name = forms.CharField(max_length=200,label='제품명',
                    widget=forms.TextInput(attrs={'placeholder':'제품명을 입력하세요'})
                    )
    description = forms.CharField(required=False,label='제품설명',
                    widget=forms.Textarea(attrs={'rows':4,'placeholder':'제품설명을 입력하세요'}))
    price = forms.FloatField(label='제품가격',
                    widget=forms.NumberInput(attrs={'min':0,'step':0.01,'placeholder':'제품가격을 입력하세요'}))
    stock = forms.IntegerField(initial=0, label='재고수량',
                    widget=forms.NumberInput(attrs={'min':0,'placeholder':'재고수량을 입력하세요'}))
 

Django-FastApi-Integration/django-project/products/views.py
from django.shortcuts import render, redirect
from django.conf import settings
import httpx
from .forms import ProductForm
from django.contrib import messages
# Create your views here.

FASTAPI_URL = settings.FASTAPI_BASE_URL

async def get_products():
    async with httpx.AsyncClient() as client:  # 비동기 http 커넥션
        try:
            response = await client.get(f'{FASTAPI_URL}/api/products')
            response.raise_for_status()  # 오류 발생시 예외 발생
            return response.json()
        except httpx.HTTPError as e:
            print(f"Error fetching products: {e}")
            return []
# 아이디에 대한 제품 조회 함수
async def get_product(product_id):
    async with httpx.AsyncClient() as client:  # 비동기 http 커넥션
        try:
            response = await client.get(f'{FASTAPI_URL}/api/products/{product_id}')
            response.raise_for_status()  # 오류 발생시 예외 발생
            return response.json()
        except httpx.HTTPError as e:
            print(f"Error fetching products: {e}")
            return None

async def create_product(data):
    async with httpx.AsyncClient() as client:  # 비동기 http 커넥션
        try:
            response = await client.post(f'{FASTAPI_URL}/api/products',json=data)
            response.raise_for_status()  # 오류 발생시 예외 발생
            return response.json()
        except httpx.HTTPError as e:
            print(f"Error creating product: {e}")
            return None

async def update_product(product_id, data):
    async with httpx.AsyncClient() as client:  # 비동기 http 커넥션
        try:
            response = await client.put(f'{FASTAPI_URL}/api/products/{product_id}',json=data)
            response.raise_for_status()  # 오류 발생시 예외 발생
            return response.json()
        except httpx.HTTPError as e:
            print(f"Error creating product: {e}")
            return None


###############################################################################################################

async def product_list(request):
    products = await get_products()
    return render(request,'products/product_list.html',{'products': products})


async def product_create(request):
    if request.method == 'GET':
        form = ProductForm()
    elif request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            # 폼에서 데이터 추출
            data = form.cleaned_data
            result = await create_product(data)
            if result:
                messages.success(request, '제품이 성공적으로 생성되었습니다.')
                return redirect('products:product_list')  # url 별칭
            else:
                messages.error(request, '제품 생성에 실패했습니다.')
    return render(request, 'products/product_form.html', {'form': form,'title':'제품등록'})


async def product_edit(request, product_id):
    # 아이디로 제품 조회 후 사용자가 전달한 값으로 업데이트 fastapi 요청
    product = await get_product(product_id)
    if not product:
        messages.error(request, '제품을 찾을 수 없습니다.')
        return redirect('products:product_list')
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            result = await update_product(product_id, data)
            if result:
                messages.success(request, '제품이 성공적으로 수정되었습니다.')
                return redirect('products:product_list')
            else:
                messages.error(request, '제품 수정에 실패했습니다.')
    else:
        form = ProductForm(initial=product)  # 폼을 호출하면서 product 값으로 초기화
    return render(request, 'products/product_form.html', 
                  {'form': form,'title':'제품수정'}
                  )

async def product_delete(request, product_id):
    # 해당 아이디의 제품이 있는지 확인하고 삭제 요청을 FastAPI로 보냄
    product = await get_product(product_id)    
    if not product:
        messages.error(request, '제품을 찾을 수 없습니다.')
        return redirect('products:product_list')    
    if request.method == 'POST':
        async with httpx.AsyncClient() as client:
            try:
                response = await client.delete(f'{FASTAPI_URL}/api/products/{product_id}')
                response.raise_for_status()
                messages.success(request, '제품이 성공적으로 삭제되었습니다.')
                return redirect('products:product_list')
            except httpx.HTTPError as e:
                messages.error(request, '제품 삭제에 실패했습니다.')
                return False

Django-FastApi-Integration/django-project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body{
            padding-top: 20px;
            background-color: azure;
        }
        .container{
            max-width:1200px
        }
    </style>
</head>
<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

Django-FastApi-Integration/django-project/templates/products/product_form.html
{% extends 'base.html' %}

{% block title %} {{title}} {% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        <div class="mb-3">
            {{form.name}}
        </div>
        <div class="mb-3">
            {{form.description}}
        </div>
        <div class="mb-3">
            {{form.price}}
        </div>
        <div class="mb-3">
            {{form.stock}}
        </div>
        <button type="submit" class="btn btn-success">저장</button>
    </form>
{% endblock %}

Django-FastApi-Integration/django-project/templates/products/product_list.html
{% extends 'base.html' %}

{% block title %} 제품리스트  {% endblock %}

{% block content %}
<table class="table">
  <thead>
    <tr>      
      <th scope="col">제품명</th>
      <th scope="col">가격</th>
      <th scope="col">수량</th>
      <th scope="col">비고</th>
      <th scope="col">*</th>
    </tr>
  </thead>
  <tbody>    
    {% for product in products%}
    <!-- ajax로 호출할때 클릭이벤트를 this로 받아서 그런데 동적생성이기 때문에 부모을 통해서 (이벤트 위임) -->
    <tr data-product-id = "{{ product.id }}"> 
        <td>{{ product.name }}</td>
        <td>{{ product.price }}</td>
        <td>{{ product.stock }}</td>
        <td>{{ product.description }}</td>
        <td>
            <a href="{% url 'products:product_edit' product.id %}" class="btn btn-primary btn-sm">수정</a>
            <form method="post" 
              action = "{% url 'products:product_delete' product.id %}" 
              style="display:inline;"
              onsubmit="return confirm('정말 삭제하시겠습니까?');"
              >
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm">삭제</button>
            </form>
        </td>
    </tr>
    {% endfor %}
    
  </tbody>
</table>    
{% endblock %}