Django/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [    
    # http://127.0.0.1:800/blog/
    path('', views.index),   # http://127.0.0.1:8000/blog/
    path('<int:question_id>/', views.detail,name='detail'),  # alies 별칭 name = 이름  상세페이지
    path('register/answer/<int:question_id>/', views.answer_create, name='answer_create'),
]

Django/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls') ),
]

Django/blog/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)

Django/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Question
from django.shortcuts import render
# Create your views here.
def index(request):
    question_list =  Question.objects.order_by('-create_at')
    context = {'question_list' : question_list}
    return render(request,'blog/question_list.html',context)

def detail(request,question_id):
    question = Question.objects.get(id=question_id)
    context = {'question':question}
    return render(request,'blog/question_detail.html',context)

from django.utils import timezone
from django.shortcuts import redirect
def answer_create(request, question_id):  # url로 넘어온 데이터
    question = Question.objects.get(id=question_id)
    question.answer_set.create(content=request.POST.get('content'),create_at=timezone.now())
    return redirect('blog:detail',question_id=question.id)

Django/templates/blog/question_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>상세내용</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body class="container">
    {% if question %}
        <p>{{question.content}}</p>
        <p>{{question.create_at}}</p>
    {% else %}
        <p>존재하지 않는 질문입니다.</p>
    {% endif %}
    <hr>
        <h5>{{question.answer_set.count}} 개의 답변이 있습니다.</h5>
        <ul>
            {% for answer in question.answer_set.all %}
                <li>{{answer.content}}</li>
            {% endfor %}
        </ul>
    <hr>
    <h3>뎃글</h3>
    <form action="{% url 'blog:answer_create' question.id %}" method="post">
        {% csrf_token %}
        <textarea name="content" row="20"></textarea>
        <button type="submit">등록</button>
    </form>
</body>
</html>

Django/templates/blog/question_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>질문목록</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body class="container">
    <h1>질문목록</h1>
    {% if  question_list %}
        <ul>
        {% for question in question_list %}
            <li>
                <!-- <a href="/blog/{{ question.id }}/">{{ question.subject }}</a> -->
                 <a href="{% url 'blog:detail' question.id %}">{{ question.subject }}</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>질문이 없습니다.</p>
    {% endif %}
</h1>
</body>
</html>